pipeline{
    agent { label 'nodejs' }
    stages{
        stage('clone'){
            steps {
                git url:'https://github.com/Mypracticeclassoct-dec/js-e2e-express-server_jan2023.git', branch:'main'
            }
        }
        stage('npmpackage'){
            steps {
                sh 'npm install'
                sh 'npm start'
            }
        }
    }
}